[2025-06-05T16:51:31.723+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-05T16:51:31.833+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cpwd_tender_etl.extract_task manual__2025-06-05T16:51:18.424474+00:00 [queued]>
[2025-06-05T16:51:31.944+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cpwd_tender_etl.extract_task manual__2025-06-05T16:51:18.424474+00:00 [queued]>
[2025-06-05T16:51:32.049+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-06-05T16:51:32.357+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_task> on 2025-06-05 16:51:18.424474+00:00
[2025-06-05T16:51:32.398+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=115) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-05T16:51:32.417+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cpwd_tender_etl', 'extract_task', 'manual__2025-06-05T16:51:18.424474+00:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/tender_etl.py', '--cfg-path', '/tmp/tmp3jxuu5rz']
[2025-06-05T16:51:32.482+0000] {standard_task_runner.py:72} INFO - Started process 125 to run task
[2025-06-05T16:51:32.511+0000] {standard_task_runner.py:105} INFO - Job 209: Subtask extract_task
[2025-06-05T16:51:33.821+0000] {task_command.py:467} INFO - Running <TaskInstance: cpwd_tender_etl.extract_task manual__2025-06-05T16:51:18.424474+00:00 [running]> on host 870c720175b3
[2025-06-05T16:51:34.371+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cpwd_tender_etl' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-05T16:51:18.424474+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-05T16:51:18.424474+00:00'
[2025-06-05T16:51:34.398+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-06-05T16:51:34.415+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-06-05T16:51:34.429+0000] {logging_mixin.py:190} INFO - Current task name:extract_task state:running start_date:2025-06-05 16:51:31.898519+00:00
[2025-06-05T16:51:34.446+0000] {logging_mixin.py:190} INFO - Dag name:cpwd_tender_etl and current dag run status:running
[2025-06-05T16:51:34.462+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-06-05T16:51:35.714+0000] {tender_etl.py:39} ERROR - Could not find tender table on the page.
[2025-06-05T16:51:35.745+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tender_etl.py", line 40, in extract_data
    raise ValueError("Tender table not found")
ValueError: Tender table not found
[2025-06-05T16:51:36.283+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-06-05T16:51:36.294+0000] {logging_mixin.py:190} INFO - Task start:2025-06-05 16:51:31.898519+00:00 end:2025-06-05 16:51:36.281168+00:00 duration:4.382649
[2025-06-05T16:51:36.317+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_task> dag:<DAG: cpwd_tender_etl> dagrun:<DagRun cpwd_tender_etl @ 2025-06-05 16:51:18.424474+00:00: manual__2025-06-05T16:51:18.424474+00:00, state:running, queued_at: 2025-06-05 16:51:18.479804+00:00. externally triggered: True>
[2025-06-05T16:51:36.350+0000] {logging_mixin.py:190} INFO - Failure caused by Tender table not found
[2025-06-05T16:51:36.384+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=cpwd_tender_etl, task_id=extract_task, run_id=manual__2025-06-05T16:51:18.424474+00:00, execution_date=20250605T165118, start_date=20250605T165131, end_date=20250605T165136
[2025-06-05T16:51:36.605+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-06-05T16:51:36.639+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 209 for task extract_task (Tender table not found; 125)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tender_etl.py", line 40, in extract_data
    raise ValueError("Tender table not found")
ValueError: Tender table not found
[2025-06-05T16:51:36.808+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-05T16:51:36.993+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-05T16:51:37.039+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
